version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/nextjs-app
    working_dir: /app/nextjs-app
    environment:
      - NODE_ENV=development
      - TZ=Asia/Seoul
      - NEXT_PUBLIC_API_URL=http://backend:8080/api
    command: bash -c "npm install && npm run dev"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-backend
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app/spring-boot-app
    working_dir: /app/spring-boot-app
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/loadtestdemodb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - TZ=Asia/Seoul
    command: bash -c "chmod +x ./gradlew && ./gradlew clean build && java -jar build/libs/demo-0.0.1-SNAPSHOT.jar"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: loadtest-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: loadtestdemodb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      TZ: Asia/Seoul
    volumes:
      - ./db/postgres/data:/var/lib/postgresql/data
      - ./db/postgres/init:/docker-entrypoint-initdb.d
    command:
      - "postgres"
      - "-c"
      - "max_connections=100"
      - "-c"
      - "client_encoding=UTF8"

  k6:
    image: grafana/k6
    container_name: k6-load-tester
    volumes:
      - ./k6-scripts:/scripts
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    depends_on:
      - backend
    entrypoint: ["/bin/sh", "-c"]
    command: ["tail -f /dev/null"]
    # 테스트 실행 시에는 다음과 같이 실행: docker exec -it k6-load-tester k6 run /scripts/load-test.js

  influxdb:
    image: influxdb:1.8
    container_name: k6-influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:latest
    container_name: k6-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - influxdb
